### ISSUE TITLE
No message response

### ISSUE THREAD

**Issue by nanthanwa** [tejitak/node-line-bot-api#4]
in web hook router

`const promises = req.body.events.map(event => {
	return line.client
	.replyMessage({
		replyToken: event.replyToken,
		messages: [
			{
				type: 'text',
				text: event.message.text
			}
		]
	})
})
Promise
.all(promises)
.then(() => res.json({success: true}))`

It should echo the message but nothing and without any error :(

**Comment by jwilyandi19** [comment]
you should need signature header.
When I try to execute command, I got following errors instead.
`Error: A signature header is required
    at D:\Storage\Project\LineBot\node_modules\node-line-bot-api\lib\clients\v2\SignatureValidator.js:25:15
    at Layer.handle [as handle_request] (D:\Storage\Project\LineBot\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Storage\Project\LineBot\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Storage\Project\LineBot\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Storage\Project\LineBot\node_modules\express\lib\router\layer.js:95:5)
    at D:\Storage\Project\LineBot\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Storage\Project\LineBot\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Storage\Project\LineBot\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (D:\Storage\Project\LineBot\node_modules\body-parser\lib\types\json.js:119:7)
    at Layer.handle [as handle_request] (D:\Storage\Project\LineBot\node_modules\express\lib\router\layer.js:95:5)`
